# 数据库配置 / Database Configuration
# 优先使用环境变量 DATABASE_URL，如果未设置则使用下面的默认值
# Environment variable DATABASE_URL takes precedence over this default value
# 推荐：请在 .env 文件中设置真实的数据库连接信息
# Recommended: Set real database connection in .env file
mariaDBUrl: mysql://root:AyEB7kJjm4@192.168.88.10:3306/fotNet
output: ./src
