version: "3.5"

services:
  rabbitmq:
    image: "rabbitmq:3.11-management"
    hostname: rabbitmq
    networks:
      - fotNet
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - "rabbitmq_data:/var/lib/rabbitmq"
    deploy:
      restart_policy:
        condition: any
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
      - RABBITMQ_ERLANG_COOKIE=SWQOKODSQALRPCLNMEQG
      - RABBITMQ_NODENAME=rabbit@rabbitmq
      - RABBITMQ_CONFIG_FILE=/var/lib/rabbitmq/rabbitmq.conf

volumes:
  rabbitmq_data:
    driver: local

networks:
  fotNet:
    external: true