version: "3.5"
services:
  mariadb:
    image: "mariadb:10.5"
    ports:
      - "3306:3306"
    networks:
      - fotNet
    volumes:
      - "mariadb_data:/var/lib/mysql"
    environment:
      - MARIADB_CHARACTER_SET=utf8mb4
      - MARIADB_COLLATE=utf8mb4_unicode_ci
      - MARIADB_ROOT_USER=root
      - MARIADB_ROOT_PASSWORD=AyEB7kJjm4
      - MARIADB_DATABASE=fotNet
      - MARIADB_USER=fotnet_user
      - MARIADB_PASSWORD=AyEB7kJjm4

volumes:
  mariadb_data:
    driver: local
networks:
  fotNet:
    external: true