version: "3.5"

services:
  redis:
    image: docker.io/bitnami/redis
    networks:
      - fotNet
    ports:
      - "6379:6379"
    volumes:
      - "redis_data:/bitnami/redis/data"
    restart: always               
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
volumes:
  redis_data:
    driver: local
networks:
  fotNet:
    external: true